name: 'Setup Gotip'
description: 'install gotip'
inputs:
  branch:  # branch
    description: 'the branch you wish to install'
    required: false
    default: 'master'
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
    - name: Install gotip
      run: go install golang.org/dl/gotip@latest
      shell: bash
    - name: Download gotip
      run: gotip download ${{ inputs.branch }}
      shell: bash
    - name: Output
      run: gotip env
      shell: bash